The ``BaseGeometry`` module
======================

Using ``BaseGeometry``
-------------------

First import ``BaseGeometry`` from the ``7-base_geometry`` file:

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Tests:

    Test - check area method raises exception
    >>> bg = BaseGeometry()
    >>> bg.area()
    Traceback (most recent call last):
    ...
    Exception: area() is not implemented

    Test - integer_validator method with non-integer value
    >>> bg.integer_validator("age", "twenty")
    Traceback (most recent call last):
    ...
    TypeError: age must be an integer

    Test - integer_validator method with zero value
    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
    ...
    ValueError: age must be greater than 0

    Test - integer_validator method with negative value
    >>> bg.integer_validator("age", -5)
    Traceback (most recent call last):
    ...
    ValueError: age must be greater than 0

    Test - integer_validator method with valid integer
    >>> bg.integer_validator("age", 10)
    
    Test present: integer_validator()
    >>> bg.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

    Test present: integer_validator("age")
    >>> bg.integer_validator("age")
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

    Test present: integer_validator("age", (4,))
    >>> bg.integer_validator("age", (4,))
    Traceback (most recent call last):
    ...
    TypeError: age must be an integer

    Test present: integer_validator("age", [3])
    >>> bg.integer_validator("age", [3])
    Traceback (most recent call last):
    ...
    TypeError: age must be an integer

    Test present: integer_validator("age", True)
    >>> bg.integer_validator("age", True)
    Traceback (most recent call last):
    ...
    TypeError: age must be an integer

    Test present: integer_validator("age", {3, 4})
    >>> bg.integer_validator("age", {3, 4})
    Traceback (most recent call last):
    ...
    TypeError: age must be an integer
